export const Client=[
    {
        "id":1,
        "text":"Headphone & Case",
        "title":"Universal",
        "title2":"Headphone & Case",
        "price":"159.00",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/headphonecase-300x300.png"
    },
    {
        "id":2,
        "title":"Headphone USB",
        "title2":"Wireless",
        "text":"Headphone & Accessories",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/usbheadphone-300x300.png",
        "price":"159.00",
    },
    {
        "id":3,
        "title":"Ultra Wireless S50",
        "title2":"Headphones S50",
        "text":"HeadPhones",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/1-300x300.png",
        "price":"350.00",
    },
    {
        "id":4,
        "title":"Wireless Audio",
        "title2":"System Multiroom",
        "text":"Audio Speakers",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/WirelessSound-300x300.png",
        "price":"2,250.00",
    },
    {
        "id":5,
        "title":"Tablet White",
        "title2":"EliteBook Revolve",
        "text":"Laptops",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/Ultrabooks-300x300.png",
        "price":"1,300.00",
    },
    {
        "id":6,
        "title":"Purple Solo 2",
        "title2":"Wireless",
        "text":"HeadPhones",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/heade1-300x300.png",
        "price":"248.00",
    },
    {
        "id":7,
        "title":"NoteBooks",
        "title2":"WideScreen Y700-",
        "text":"Laptops",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/asuaslap-300x300.png",
        "price":"1,299.00",
    },
    {
        "id":8,
        "title":"Laptop Wifi CX61",
        "title2":"2QF 4210M",
        "text":"Laptops",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/macpro-300x300.png",
        "price":"2,299.00",
    },
    {
        "id":9,
        "title":"Laptop R752LJ",
        "title2":"5200U 4GB 1TB",
        "text":"Laptops",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/asuaslap-300x300.png",
        "price":"2,399.00",
    },
    {
        "id":10,
        "title":"Laptop Screener",
        "title2":"CX70 2QF-621XPL",
        "text":"Laptops",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/applap-300x300.png",
        "price":"1,100.00",
    },
   
    {
        "id":11,
        "title":"AeroCool EN 52377",
        "title2":"Dead Silence",
        "text":"Computer Cases",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/gamecabin-300x300.png",
        "price":"150.00",
        "price2":"$ 180.00",
    },
    {
        "id":12,
        "title":"Full Color LaserJet",
        "title2":"Pro M452dn",
        "text":"Printers",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/printer-300x300.png",
        "price":"1,050.00",
    },
    {
        "id":13,
        "title":"White MN Mini f1",
        "title2":"Smart Mx",
        "text":"Cameras",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/camera2-300x300.png",
        "price":"559.00",
    },
    {
        "id":14,
        "title":"SmartPhone 6s",
        "title2":"32 GB LTE",
        "text":"SmartPhones",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/GoldPhone-1-300x300.png",
        "price":"1,100.00",
        "price2":"$ 1,215.00",
    },
    {
        "id":15,
        "title":"PowerBank 1130",
        "title2":"mah Blue",
        "text":"PowerBank",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/powerbank-300x300.png",
        "price":"200.00",
        "price2":"$ 210.00",
    },
    {
        "id":16,
        "title":"SmartWatch 2.0 LTE",
        "title2":"Wifi Waterproof",
        "text":"SmartWatch",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/watch-300x300.png",
        "price":"700.00",
        "price2":"$ 725.00",
    },
    {
        "id":17,
        "title":"Smart Camera",
        "title2":"6200U With 500GB",
        "text":"Cameras",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/cam4k-300x300.png",
        "price":"2,999.00",
    },
    {
        "id":18,
        "title":"Wireless Charger",
        "title2":"2040 White",
        "text":"Chargers",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/whirelesscar-300x300.png",
        "price":"248.00",
    },
    {
        "id":19,
        "title":"UltraBook",
        "title2":"UX305CA-FC050T",
        "text":"SmartPhones",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/redmi-300x300.png",
        "price":"1,200.00",
        "price2":"$ 1,218.00",
    },
    {
        "id":20,
        "title":"SmartPhone 6s",
        "title2":"32GB LTE",
        "text":"SmartPhones",
        "img":"https://electro.madrasthemes.com/wp-content/uploads/2016/03/lgphone-300x300.png",
        "price":"780.00",
    }
    ]